# U2A1. PROBLEMARIO. Operaciones matriciales y vectoriales


## Ejercicio 1 - C = A + B

En este ejercicio se suman dos matrices A y B del mismo tamaño.

La suma de matrices se realiza elemento por elemento.

In [ ]:
import numpy as np
A = np.array([[2,4,6],[1,3,5],[7,9,11]])
B = np.array([[12,10,8],[6,4,2],[0,-2,-4]])
C = A + B
C

array([[14, 14, 14],
       [ 7,  7,  7],
       [ 7,  7,  7]])

## Ejercicio 2 - C = A * B

Aquí se realiza la multiplicación matricial entre A y B.
Para que la multiplicación sea válida, el número de columnas de A debe coincidir con el número de filas de B.
Cada elemento resultante se calcula como el producto punto entre una fila de
A y una columna de B.

In [ ]:
import numpy as np
A = np.array([[2,1],[3,4],[5,6]])
B = np.array([[7,8],[9,10]])
C = A.dot(B)
C

array([[ 23,  26],
       [ 57,  64],
       [ 89, 100]])

## Ejercicio 3 - A^{-1}

En este ejercicio se busca la matriz inversa A^{-1}
, siempre que el determinante de A sea distinto de cero.

La matriz inversa es aquella que cumple:

AA^{−1}=I



In [ ]:
import numpy as np
A = np.array([[4,7,2],[2,6,8],[3,1,9]], dtype=float)
np.linalg.inv(A)

array([[ 0.2371134 , -0.31443299,  0.22680412],
       [ 0.03092784,  0.15463918, -0.1443299 ],
       [-0.08247423,  0.08762887,  0.05154639]])

## Ejercicio 4 - Solución X = [x,y,z]

El sistema se escribe en forma matricial:

AX=B donde X=[x,y,z].

In [ ]:
import numpy as np
A = np.array([[2,1,1],[3,5,2],[1,2,4]], dtype=float)
B = np.array([8,21,11], dtype=float)
np.linalg.solve(A,B)

array([2.30434783, 2.43478261, 0.95652174])

## Ejercicio 5 - det(A)
Aquí se calcula el determinante de la matriz A.
El determinante indica:

Si una matriz es invertible

Si un sistema lineal tiene solución única

Información sobre transformaciones geométricas

In [ ]:
import numpy as np
A = np.array([[3,-2,1],[0,5,4],[2,1,7]], dtype=float)
np.linalg.det(A)

np.float64(67.00000000000004)

## Ejercicio 6 - A x B

El producto cruz entre dos vectores de R^3 produce un vector perpendicular a ambos.

Su magnitud representa el área del paralelogramo formado por los vectores.

In [ ]:
import numpy as np
A = np.array([2,3,-1])
B = np.array([1,-2,4])
np.cross(A,B)

array([10, -9, -7])

## Ejercicio 7 - Proyección de V sobre U

Se obtiene la proyección del vector V sobre el vector U usando la fórmula:

In [ ]:
import numpy as np
V = np.array([5,-3,2], dtype=float)
U = np.array([2,1,2], dtype=float)
(np.dot(V,U)/np.dot(U,U))*U

array([2.44444444, 1.22222222, 2.44444444])

## Ejercicio 8 - Producto escalar de proyecciones
Primero se calculan:

La proyección de V sobre U

La proyección de V sobre W

Luego se calcula el producto punto entre ambas proyecciones:

projU(V)⋅projW(V)
	​



In [ ]:
import numpy as np
V = np.array([3,-1,2], dtype=float)
U = np.array([2,2,-1], dtype=float)
W = np.array([1,4,-2], dtype=float)
projU = (np.dot(V,U)/np.dot(U,U))*U
projW = (np.dot(V,W)/np.dot(W,W))*W
np.dot(projU, projW)

np.float64(-0.6349206349206349)

## Ejercicio 9 - Vectores ortogonales (Gram-Schmidt)

In [ ]:
import numpy as np
v1 = np.array([1,1,0], dtype=float)
v2 = np.array([1,2,1], dtype=float)
v3 = np.array([2,1,3], dtype=float)
def gram_schmidt(vs):
    ortho = []
    for v in vs:
        w = v.copy()
        for u in ortho:
            w = w - (np.dot(w,u)/np.dot(u,u))*u
        ortho.append(w)
    return ortho
ortho = gram_schmidt([v1,v2,v3])
ortho

[array([1., 1., 0.]),
 array([-0.5,  0.5,  1. ]),
 array([ 1.33333333, -1.33333333,  1.33333333])]

## Ejercicio 10 - Base del espacio nulo

In [ ]:
import numpy as np

# Matriz en forma escalonada reducida
A = np.array([
    [1, 2, 0, 3],
    [0, 1, 0, 2],
    [0, 0, 1, 1]
], dtype=float)

# El espacio nulo tiene un parámetro libre t = x4
# Las ecuaciones son:
# x2 + 2 x4 = 0  -> x2 = -2 t
# x3 + x4 = 0    -> x3 = -t
# x1 + 2 x2 + 3 x4 = 0 -> x1 = t

# Por lo tanto, un vector base es:
null_basis = np.array([1, -2, -1, 1], dtype=float)

print("Base del espacio nulo:")
print(null_basis)

# Comprobación: A * null_basis debe dar el vector cero
print("\nComprobación A · v =")
print(A.dot(null_basis))


Base del espacio nulo:
[ 1. -2. -1.  1.]

Comprobación A · v =
[0. 0. 0.]
